Initial attempt at Vitest support
Menci/vite-plugin-wasm pull request #16
Opened 2022-10-24 13:03 UTC by rossng

This PR is an initial stab at enabling support for server-side rendering, which is needed for vite-plugin-wasm to work in Vitest.

I haven't tested this in detail - e.g. whether it will work in a normal Vite SSR context. But I thought it would be good to get early feedback on the approach before investing too much time.

2022-10-24 18:11 UTC, Menci requested changes

2022-10-24 18:11 UTC, Menci commented on src/wasm-parser.ts
> +    .join(", ")} }, ${names.wasmUrl}, ${JSON.stringify(rootPath)});
Will the injection of `rootPath` leak the project dir in a production build for browser?

2022-10-24 18:11 UTC, Menci commented on src/wasm-helper.ts
>    if (url.startsWith("data:")) {
Can we reuse the `url` param and use a `file://` URL for SSR?

We can generate code that pass different URL to `initWasm` according to `import.meta.env.SSR`.

2022-12-16 01:53 UTC, Menci commented
@rossng ping

2022-12-16 09:31 UTC, rossng commented
Apologies, been very busy these past few weeks! Will try to take a look over xmas/new year.

2023-01-31 18:40 UTC, AndrewJSchoen commented
Any updates on this?

2023-01-31 18:42 UTC, Menci commented
> Any updates on this?

I'm going to work on this recently.

2023-02-01 10:40 UTC, rossng commented
It doesn't look like I'm going to have the chance to work on this, so feel free to close (or reuse anything from) this PR.

2023-02-05 15:39 UTC, closed without merging